### ISSUE TITLE
DevEnvironment: Error log

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-london#68]
From mac install

```
   default: + pyvenv colouringlondon
    default: WARNING: the pyenv script is deprecated in favour of `python3.6 -m venv`
    default: + source colouringlondon/bin/activate
    default: ++ deactivate nondestructive
    default: ++ '[' -n '' ']'
    default: ++ '[' -n '' ']'
    default: ++ '[' -n /bin/bash -o -n '' ']'
    default: ++ hash -r
    default: ++ '[' -n '' ']'
    default: ++ unset VIRTUAL_ENV
    default: ++ '[' '!' nondestructive = nondestructive ']'
    default: ++ VIRTUAL_ENV=/home/vagrant/colouringlondon
    default: ++ export VIRTUAL_ENV
    default: ++ _OLD_VIRTUAL_PATH=/usr/local/lib/node/node-v8.11.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    default: ++ PATH=/home/vagrant/colouringlondon/bin:/usr/local/lib/node/node-v8.11.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    default: ++ export PATH
    default: ++ '[' -n '' ']'
    default: ++ '[' -z '' ']'
    default: ++ _OLD_VIRTUAL_PS1=
    default: ++ '[' 'x(colouringlondon) ' '!=' x ']'
    default: ++ PS1='(colouringlondon) '
    default: ++ export PS1
    default: ++ '[' -n /bin/bash -o -n '' ']'
    default: ++ hash -r
    default: + pip install --upgrade pip
    default: Collecting pip
    default:   Downloading https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl (1.4MB)
    default: Installing collected packages: pip
    default:   Found existing installation: pip 9.0.1
    default:     Uninstalling pip-9.0.1:
    default:       Successfully uninstalled pip-9.0.1
    default: Successfully installed pip-19.1.1
    default: + pip install --upgrade setuptools wheel
    default: Collecting setuptools
    default:   Downloading https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)
    default: Collecting wheel
    default:   Downloading https://files.pythonhosted.org/packages/bb/10/44230dd6bf3563b8f227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl
    default: Installing collected packages: setuptools, wheel
    default:   Found existing installation: setuptools 39.0.1
    default:     Uninstalling setuptools-39.0.1:
    default:       Successfully uninstalled setuptools-39.0.1
    default: Successfully installed setuptools-41.0.1 wheel-0.33.4
    default: + pip install -r /vagrant/etl/requirements.txt
    default: Collecting fiona==1.7.13 (from -r /vagrant/etl/requirements.txt (line 2))
    default:   Downloading https://files.pythonhosted.org/packages/e3/bf/029958f4e3811ce7017fb5805d5203e8bde6c1816b902964acb2dec67863/Fiona-1.7.13-cp36-cp36m-manylinux1_x86_64.whl (15.8MB)
    default: Collecting osmnx==0.8.1 (from -r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/c7/ab/29f315dbbbca2e66dd60486ac130af19826a175ddb15e823695a4e9cb68a/osmnx-0.8.1-py2.py3-none-any.whl (64kB)
    default: Collecting psycopg2==2.7.5 (from -r /vagrant/etl/requirements.txt (line 4))
    default:   Downloading https://files.pythonhosted.org/packages/5e/d0/9e2b3ed43001ebed45caf56d5bb9d44ed3ebd68e12b87845bfa7bcd46250/psycopg2-2.7.5-cp36-cp36m-manylinux1_x86_64.whl (2.7MB)
    default: Collecting shapely==1.6.4 (from -r /vagrant/etl/requirements.txt (line 5))
    default:   Downloading https://files.pythonhosted.org/packages/bd/f2/9f5f3cb42ce722aef3341cbbe7ed54aed6e198c75b5f08fcc1265eb3499d/Shapely-1.6.4-cp36-cp36m-manylinux1_x86_64.whl (1.5MB)
    default: Collecting six>=1.7 (from fiona==1.7.13->-r /vagrant/etl/requirements.txt (line 2))
    default:   Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
    default: Collecting click-plugins (from fiona==1.7.13->-r /vagrant/etl/requirements.txt (line 2))
    default:   Downloading https://files.pythonhosted.org/packages/e9/da/824b92d9942f4e472702488857914bdd50f73021efea15b4cad9aca8ecef/click_plugins-1.1.1-py2.py3-none-any.whl
    default: Collecting cligj>=0.4 (from fiona==1.7.13->-r /vagrant/etl/requirements.txt (line 2))
    default:   Downloading https://files.pythonhosted.org/packages/e4/be/30a58b4b0733850280d01f8bd132591b4668ed5c7046761098d665ac2174/cligj-0.5.0-py3-none-any.whl
    default: Collecting munch (from fiona==1.7.13->-r /vagrant/etl/requirements.txt (line 2))
    default:   Downloading https://files.pythonhosted.org/packages/68/f4/260ec98ea840757a0da09e0ed8135333d59b8dfebe9752a365b04857660a/munch-2.3.2.tar.gz
    default: Collecting descartes>=1.1 (from osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/e5/b6/1ed2eb03989ae574584664985367ba70cd9cf8b32ee8cad0e8aaeac819f3/descartes-1.1.0-py3-none-any.whl
    default: Collecting requests>=2.18 (from osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
    default: Collecting numpy>=1.14 (from osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/87/2d/e4656149cbadd3a8a0369fcd1a9c7d61cc7b87b3903b85389c70c989a696/numpy-1.16.4-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
    default: Collecting geopandas>=0.3 (from osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/74/42/f4b147fc7920998a42046d0c2e65e61000bc5d104f1f8aec719612cb2fc8/geopandas-0.5.0-py2.py3-none-any.whl (893kB)
    default: Collecting networkx>=2.1 (from osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/85/08/f20aef11d4c343b557e5de6b9548761811eb16e438cee3d32b1c66c8566b/networkx-2.3.zip (1.7MB)
    default: Collecting pandas>=0.22 (from osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/19/74/e50234bc82c553fecdbd566d8650801e3fe2d6d8c8d940638e3d8a7c5522/pandas-0.24.2-cp36-cp36m-manylinux1_x86_64.whl (10.1MB)
    default: Collecting Rtree>=0.8.3 (from osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/33/0d/0bcb0fdd759570e85697189f675fa462131e5636482f2832288bbe4bb6f7/Rtree-0.8.3-py3-none-any.whl
    default: Collecting matplotlib>=2.2 (from osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/da/83/d989ee20c78117c737ab40e0318ea221f1aed4e3f5a40b4f93541b369b93/matplotlib-3.1.0-cp36-cp36m-manylinux1_x86_64.whl (13.1MB)
    default: Collecting click>=4.0 (from click-plugins->fiona==1.7.13->-r /vagrant/etl/requirements.txt (line 2))
    default:   Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
    default: Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.18->osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl (150kB)
    default: Collecting certifi>=2017.4.17 (from requests>=2.18->osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl (157kB)
    default: Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.18->osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    default: Collecting idna<2.9,>=2.5 (from requests>=2.18->osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    default: Collecting pyproj (from geopandas>=0.3->osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/ac/1a/81ef33d97354eb7d1765a921ecaf2ece41fd7927937b7c74124b6a2a0d99/pyproj-2.2.0-cp36-cp36m-manylinux1_x86_64.whl (11.2MB)
    default: Collecting decorator>=4.3.0 (from networkx>=2.1->osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
    default: Collecting pytz>=2011k (from pandas>=0.22->osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl (510kB)
    default: Collecting python-dateutil>=2.5.0 (from pandas>=0.22->osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
    default: Requirement already satisfied: setuptools in ./colouringlondon/lib/python3.6/site-packages (from Rtree>=0.8.3->osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3)) (41.0.1)
    default: Collecting cycler>=0.10 (from matplotlib>=2.2->osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
    default: Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib>=2.2->osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl (62kB)
    default: Collecting kiwisolver>=1.0.1 (from matplotlib>=2.2->osmnx==0.8.1->-r /vagrant/etl/requirements.txt (line 3))
    default:   Downloading https://files.pythonhosted.org/packages/f8/a1/5742b56282449b1c0968197f63eae486eca2c35dcd334bab75ad524e0de1/kiwisolver-1.1.0-cp36-cp36m-manylinux1_x86_64.whl (90kB)
    default: Building wheels for collected packages: munch, networkx
    default:   Building wheel for munch (setup.py): started
    default:   Building wheel for munch (setup.py): finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/db/bf/bc/06a3e1bfe0ab27d2e720ceb3cff3159398d92644c0cec2c125
    default:   Building wheel for networkx (setup.py): started
    default:   Building wheel for networkx (setup.py): finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/de/63/64/3699be2a9d0ccdb37c7f16329acf3863fd76eda58c39c737af
    default: Successfully built munch networkx
    default: Installing collected packages: six, click, click-plugins, cligj, munch, fiona, cycler, numpy, python-dateutil, pyparsing, kiwisolver, matplotlib, descartes, urllib3, certifi, chardet, idna, requests, pytz, pandas, shapely, pyproj, geopandas, decorator, networkx, Rtree, osmnx, psycopg2
    default: Successfully installed Rtree-0.8.3 certifi-2019.6.16 chardet-3.0.4 click-7.0 click-plugins-1.1.1 cligj-0.5.0 cycler-0.10.0 decorator-4.4.0 descartes-1.1.0 fiona-1.7.13 geopandas-0.5.0 idna-2.8 kiwisolver-1.1.0 matplotlib-3.1.0 munch-2.3.2 networkx-2.3 numpy-1.16.4 osmnx-0.8.1 pandas-0.24.2 psycopg2-2.7.5 pyparsing-2.4.0 pyproj-2.2.0 python-dateutil-2.8.0 pytz-2019.1 requests-2.22.0 shapely-1.6.4 six-1.12.0 urllib3-1.25.3
    default: + chown -R vagrant:vagrant /home/vagrant/colouringlondon
    default: + npm install -g npm@next
    default: /usr/local/lib/node/node-v8.11.3/bin/npm -> /usr/local/lib/node/node-v8.11.3/lib/node_modules/npm/bin/npm-cli.js
    default: /usr/local/lib/node/node-v8.11.3/bin/npx -> /usr/local/lib/node/node-v8.11.3/lib/node_modules/npm/bin/npx-cli.js
    default: + npm@6.9.1-next.0
    default: added 312 packages, removed 364 packages and updated 53 packages in 7.59s
    default: + cd /vagrant/app
    default: + npm install
    default: npm
    default:  
    default: ERR!
    default:  
    default: path
    default:  /vagrant/app/node_modules/@babel/runtime/node_modules/regenerator-runtime/package.json.2948920491
    default: npm
    default:  
    default: ERR!
    default:  
    default: code
    default:  ENOENT
    default: npm
    default:  
    default: ERR!
    default:  
    default: errno
    default:  -2
    default: npm
    default:  
    default: ERR!
    default:  
    default: syscall
    default:  open
    default: npm
    default:  
    default: ERR!
    default:  
    default: enoent
    default:  ENOENT: no such file or directory, open '/vagrant/app/node_modules/@babel/runtime/node_modules/regenerator-runtime/package.json.2948920491'
    default: npm
    default:  
    default: ERR!
    default:  
    default: enoent
    default:  This is related to npm not being able to find a file.
    default: npm
    default:  
    default: ERR!
    default:  
    default: enoent
    default:  
    default: npm
    default:  
    default: ERR!
    default:  A complete log of this run can be found in:
    default: npm
    default:  
    default: ERR!
    default:      /root/.npm/_logs/2019-06-20T13_59_38_392Z-debug.log
    default: + tr -d '\r'
    default: + chown vagrant:vagrant /home/vagrant/.bashrc
```
